name: Build and Release Python Executable

on:
  push:
    tags:
      - "v*.*.*" # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository with Node.js v16 or v20 support
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pyinstaller

      # Build the executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name UndyingOverlay.exe overlay.py

      # Upload the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/

      - name: List files in dist
        run: ls dist/

  release:
    needs: build
    runs-on: windows-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Upload the executable to the release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/UndyingOverlay.exe # Specify the files to upload to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub provides this secret automatically
