# Example GitHub Actions workflow
name: Build and Release Python Executable

on:
  push:
    tags:
      - "v*.*.*" # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Use Python 3.x (set to your version)

      # Install dependencies (if you have any)
      - name: Install dependencies
        run: |
          pip install pyinstaller

      # Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed overlay.py

      # Upload the build artifact with v4
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Upload the executable to the release using v4
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          files: dist/* # Upload all files in the dist/ directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
